version: "3"
services:
  app:
    image: node:12-alpine
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.4.7
    volumes:
      - ./data:/data/db
